#!/usr/bin/env python

Import("env")

env_ewbik = env.Clone()
env_ewbik.Prepend(CPPPATH=['#thirdparty/ewbik'])
env_ewbik.Prepend(CPPPATH=['#thirdparty/ewbik/constraints'])
env_ewbik.Prepend(CPPPATH=['#thirdparty/ewbik/math'])
env_ewbik.add_source_files(env.modules_sources, "constraints/*.cpp")
env_ewbik.add_source_files(env.modules_sources, "math/*.cpp")
env_ewbik.add_source_files(env.modules_sources, "*.cpp")

if env["tools"]:
    env_ewbik.add_source_files(env.modules_sources, "editor/*.cpp")
