#!/usr/bin/env python

Import("env")

env_many_bone_ik = env.Clone()
env_many_bone_ik.Prepend(CPPPATH=["."])
env_many_bone_ik.Prepend(CPPPATH=["src/math"])
env_many_bone_ik.Prepend(CPPPATH=["src"])
env_many_bone_ik.add_source_files(env.modules_sources, "constraints/*.cpp")
env_many_bone_ik.add_source_files(env.modules_sources, "src/math/*.cpp")
env_many_bone_ik.add_source_files(env.modules_sources, "src/*.cpp")
env_many_bone_ik.add_source_files(env.modules_sources, "*.cpp")

if env.editor_build:
    env_many_bone_ik.add_source_files(env.modules_sources, "editor/*.cpp")
